# Generated by Django 6.1 on 2026-08-30 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Governador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('partido', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('inicio_mandato', models.DateField()),
                ('fim_mandato', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('orgao', models.CharField(max_length=150)),
                ('fonte_url', models.URLField()),
                ('governador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='gastos_politicos.governador')),
            ],
        ),
    ]
