# Generated by Django 6.1 on 2026-08-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos_politicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governador',
            name='fim_mandato',
            field=models.DateField(blank=True, null=True),
        ),
    ]
