# Generated by Django 6.1 on 2026-08-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos_politicos', '0003_seed_governadores_pb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
